Django_allthink/urls.py
import os
from django.conf.urls.defaults import *
from Allthink.views import *
from django.contrib import admin
from ajax_select import urls as ajax_select_urls
import settings

admin.autodiscover()

urlpatterns = patterns('',

    # Browsing
    (r'^$', main_page),
    (r'^admin/', include(admin.site.urls)),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^user/(\w+)/$', user_page),
    (r'^user/(\w+)/lesson/create/$', create_lesson),
    (r'^user/(\w+)/lesson/(\w+)/view/(\w+)/(\w+)/$', view_lesson),
    (r'^user/(\w+)/lesson/(\w+)/edit/$', edit_lesson),
    (r'^user/(\w+)/lesson/(\w+)/delete/$', delete_lesson),
    (r'^user/(\w+)/lesson/(\w+)/edit-info/$', edit_lesson_info),

    (r'^user/(\w+)/lesson/(\w+)/add-video/$', add_video),
    (r'^user/(\w+)/lesson/(\w+)/add-doc/$', add_doc),
    (r'^user/(\w+)/lesson/(\w+)/add-image/$', add_image),
    (r'^user/(\w+)/lesson/(\w+)/add-step/$', add_step),
    (r'^user/(\w+)/lesson/(\w+)/add-text/$', add_text),

    (r'^user/(\w+)/lesson/(\w+)/video/(\w+)/edit/$', edit_video),
    (r'^user/(\w+)/lesson/(\w+)/doc/(\w+)/edit/$', edit_doc),
    (r'^user/(\w+)/lesson/(\w+)/image/(\w+)/edit/$', edit_image),
    (r'^user/(\w+)/lesson/(\w+)/step/(\w+)/edit/$', edit_step),
    (r'^user/(\w+)/lesson/(\w+)/text/(\w+)/edit/$', edit_text),

    (r'^user/(\w+)/lesson/(\w+)/video/(\w+)/delete/$', delete_video),
    (r'^user/(\w+)/lesson/(\w+)/doc/(\w+)/delete/$', delete_doc),
    (r'^user/(\w+)/lesson/(\w+)/image/(\w+)/delete/$', delete_image),
    (r'^user/(\w+)/lesson/(\w+)/step/(\w+)/delete/$', delete_step),
    (r'^user/(\w+)/lesson/(\w+)/text/(\w+)/delete/$', delete_text),

    # Download file
    (r'^user/(\w+)/download/(\w+)/$', download_doc_file),

    # Browsing for student
    (r'^user/(\w+)/lesson/(\w+)/addref/$', student_addref),
    (r'^user/(\w+)/lesson/(\w+)/removeref/$', student_removeref),
    # Session management
    (r'^login/$', login),
    (r'^logout/$', logout_page),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
         { 'document_root': settings.STATIC_ROOT }),
    (r'^storages/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT }),
    (r'^signup/$', register_page),
    (r'^signup/teacher/$', teacher_register_page),
    (r'^signup/student/$', student_register_page),
    url(r'^search_form',  view='Allthink.views.search_form',name='search_form'),
    (r'^admin/lookups/', include(ajax_select_urls)),
    (r'^user/(\w+)/account/$', user_edit_page),
    (r'^user/(\w+)/pic/$', user_avatar_page),
    (r'^files/$', add_doc),
)

Django_allthink/Allthink/forms.py
# -*- coding: utf-8 -*-
import re
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.forms.widgets import *


class LoginForm(forms.Form) :
    username = forms.CharField(label="Username", max_length=30)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    remember_me = forms.BooleanField(label="Remember me", required=False, initial= True)

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label='Password (Again)',
        widget=forms.PasswordInput()
    )

    fullname = forms.CharField (label='Your name', max_length=30)

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only containal phanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords do not match.')

class EditAccountForm(forms.Form):
    username = forms.CharField(label='Username', widget= TextInput(attrs={'readonly':'readonly', 'disabled' : 'disabled'}), max_length=30)
    email = forms.EmailField(label='Email', widget= TextInput(attrs={'readonly':'readonly', 'disabled' : 'disabled'}))
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label='Password (Again)',
        widget=forms.PasswordInput()
    )

    password0 = forms.CharField(
        label='Current password',
        widget=forms.PasswordInput()
    )

    fullname = forms.CharField (label='Your name', max_length=30)

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords do not match.')

class CreateLesson(forms.Form) :
    #
    lessonTitle = forms.CharField(label="Lesson title", max_length=100)
    GRADE_LEVEL = (
        ('all','All grade level') ,
        ('e' , 'Elementary') ,
        ('h' , 'High school') ,
        ('c' , 'College')
    )
    gradeLevel = forms.ChoiceField(label="Grade level", widget= Select, choices= GRADE_LEVEL)
    SUBJECT = (
        ('math', 'Math'),
        ('science', 'Science'),
        ('physic', 'Physic')
    )
    subject = forms.ChoiceField(label="Subject", widget= Select  , choices = SUBJECT)
    description = forms.CharField(label="description", widget= Textarea(attrs={'cols': 70, 'rows': 5, 'style' : 'resize: none;'}), max_length=2000)


class AddVideoForm(forms.Form):
    pageTitle = forms.CharField(label= 'pageTitle', max_length=100)
    url = forms.URLField(label='url')
    text = forms.CharField(label="text", widget= Textarea(attrs={'cols': 70, 'rows': 5, 'style' : 'resize: none;'}), max_length=2000 , required= False)


class AddDocumentForm(forms.Form):
    pageTitle = forms.CharField(label= 'pageTitle', max_length=100, required= False)
    FILES = (
        ('non', 'non'),
        )
    selectFile = forms.ChoiceField(label="selectFile", widget= Select  , choices = FILES, required= False)
    text = forms.CharField(label="text", widget= Textarea(attrs={'cols': 70, 'rows': 5, 'style' : 'resize: none;'}), max_length=2000, required= False)


class AddImageForm(forms.Form):
    pageTitle = forms.CharField(label= 'pageTitle', max_length=100)
    FILES = (
        )
    selectFile = forms.ChoiceField(label="selectFile", widget= Select  , choices = FILES, required= False)
    text = forms.CharField(label="text", widget= Textarea(attrs={'cols': 70, 'rows': 5, 'style' : 'resize: none;'}), max_length=2000, required= False)

class AddStepbyStepForm(forms.Form):
    pageTitle = forms.CharField(label= 'pageTitle', max_length=100)
    promt = forms.CharField(label= 'promt', widget= Textarea(attrs={'cols': 65, 'rows': 4, 'style' : 'resize: none;'}), max_length=300)
    step1 = forms.CharField(label= 'step1', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain1 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step2 = forms.CharField(label= 'step2', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain2 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step3 = forms.CharField(label= 'step3', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain3 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step4 = forms.CharField(label= 'step4', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain4 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step5 = forms.CharField(label= 'step5', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain5 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step6 = forms.CharField(label= 'step6', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain6 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step7 = forms.CharField(label= 'step7', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain7 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step8 = forms.CharField(label= 'step8', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain8 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step9 = forms.CharField(label= 'step9', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain9 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step10 = forms.CharField(label= 'step10', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain10 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step11 = forms.CharField(label= 'step11', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain11 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step12 = forms.CharField(label= 'step12', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain12 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step13 = forms.CharField(label= 'step13', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain13 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step14 = forms.CharField(label= 'step14', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain14 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step15 = forms.CharField(label= 'step15', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain15 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step16 = forms.CharField(label= 'step16', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    explain16 = forms.CharField(label= 'Explaination', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)
    step17 = forms.CharField(label= 'step17', widget= Textarea(attrs={'cols': 30, 'rows': 1, 'style' : 'resize: none;'}), max_length=100, required=False)

Django_allthink/templates/account.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="vi" lang="vi">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Allthink Lessons - Profile edit</title>
    <meta name="description" content="">
    <link rel="shortcut icon" href="/site_media/images/favicon.ico">
    <link rel="stylesheet" type="text/css" href="/site_media/css/global.css">
    <script type="text/javascript" src="/site_media/js/common.js"></script>
</head>
<body>

<div id="wrapper">
    <div id="navwrapper" class="notranslate">
        <ul class="topnav" style="float: right;">
            <li>
                <a href="/user/{{ username }}/" class="nav" style="color:rgb(213,213,240);">
                    <img src="/{{ avatar_dir }}">
                    {{ fullname }} </a>
            </li>
            <li>
                <a href="/logout/" class="nav" style="color:rgb(213,213,240);">
                    Logout </a>
            </li>
        </ul>
        <a href="/user/{{ username }}/" id="logo" class="gradebook" title="gradebook"><b>gradebook</b></a>
        <ul class="topnav">
            <li>
                <a href="/user/{{ username }}/account" class="">Account </a>
                <ul>
                    <li><a href="/user/{{ username }}/account">Edit Account</a></li>
                    <li><a href="/user/{{ username }}/pic">Edit Picture</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div id="main" class="clearfix">
        <h1>Allthink Lessons</h1>

        <div class="tr">

            <div class="sidetools sideup">
                <img src="/{{ avatar_dir }}" class="sidepic">
            </div>

            <div style="position:absolute;left:200px;top:90px;right:0;bottom:0;z-index:2">

                {% if status == 'noError' %}
                    <div class="msg success">Your profile has been updated.</div>
                {% endif %}

                {% if status == 'hasError' %}
                    <div class="msg error">There were some errors with your submission</div>
                {% endif %}
                <form method="post" id="inform" action=".">
                    {% csrf_token %}
                    <div class="table inform inhelp">
                        <div class="toprow">
                            <div class="title">Edit Account</div>
                        </div>

                        <div class="row alt text ">
                            <b>{{ form.fullname.errors }} </b>
                            <div class="name "> <label for="id_fullname">  Your Name </label></div>
                            <div class="field" style="">{{ form.fullname }}</div>
                            <div class="help">Enter your full name</div>
                        </div>

                        <div class="row alt text ">
                            <b>{{ form.username.errors }} </b>
                            <div class="name "> <label for="id_username"> Choose Username </label> </div>
                            <div class="field" style="">{{ form.username }}</div>
                            <div class="help">Choose username, letters and numbers only. Students will see this.</div>
                        </div>

                        <div class="row  text ">
                            <b>{{ form.email.errors }} </b>
                            <div class="name "> <label for="id_email"> Your Email </label></div>
                            <div class="field" style="">{{ form.email }}</div>
                            <div class="help">Enter your OFFICIAL work email address</div>
                        </div>

                    </div>
                    <div class="table inform inhelp">
                        <div class="row  text ">
                            <b>{{ form.password1.errors }} </b>
                            <div class="name"> <label for="id_password">Choose Password</label> </div>
                            <div class="field" >{{ form.password1 }}</div>
                            <div class="help">Enter a new password (YOU MUST TYPE IN THIS FIELD)</div>
                        </div>

                        <div class="row alt text ">
                            <b>{{ form.password2.errors }} </b>
                            <div class="name"> <label for="id_password2">Confirm Password </label> </div>
                            <div class="field">{{ form.password2 }}</div>
                            <div class="help">Enter above password (YOU MUST TYPE IN THIS FIELD)</div>
                        </div>
                    </div>
                    <div class="table inform inhelp">
                        <div class="toprow">
                            <div class="title">Security</div>
                        </div>

                        <div class="row  text ">
                            <b>{{ form.password0.errors }} </b>
                            <div class="name"> <label for="id_password0">Current Password</label> </div>
                            <div class="field" >{{ form.password0 }}</div>
                            <div class="help">For security, enter your current password</div>
                        </div>

                        <div class="row  submit">
                            <div class="name">&nbsp;</div>
                            <div class="field">
                                <input type="submit" name="submit" value="Submit" id="formsubmit" class="submit">
                            </div>
                        </div>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>


<!--

-->


</body>
</html>

Django_allthink/templates/avatar.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="vi" lang="vi">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="shortcut icon" href="/site_media/images/favicon.ico">
    <title>Allthink Lessons - Change avatar</title>
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="/site_media/css/global.css">
    <script type="text/javascript" src="/site_media/js/common.js"></script>
</head>
<body>

<div id="wrapper">
    <div id="navwrapper" class="notranslate">
        <ul class="topnav" style="float: right;">
            <li>
                <a href="/user/{{ username }}/" class="nav" style="color:rgb(213,213,240);">
                    <img src="/{{ avatar_dir }}">
                    {{ fullname }} </a>
            </li>
            <li>
                <a href="/logout/" class="nav" style="color:rgb(213,213,240);">
                    Logout </a>
            </li>
        </ul>
        <a href="/user/{{ username }}/" id="logo" class="gradebook" title="gradebook"><b>gradebook</b></a>
        <ul class="topnav">
            <li>
                <a href="/user/{{ username }}/account" class="">Account </a>
                <ul>
                    <li><a href="/user/{{ username }}/account">Edit Account</a></li>
                    <li><a href="/user/{{ username }}/pic">Edit Picture</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div id="main" class="clearfix">
        <h1>Allthink Lessons</h1>

        <div class="tr">

            <div class="sidetools sideup">
                <img src="/{{ avatar_dir }}" class="sidepic">
            </div>

            <div style="position:absolute;left:200px;top:90px;right:0;bottom:0;z-index:2">

                <form method="post" id="inform" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="table inform">
                        <div class="toprow">
                            <div class="title">Upload Picture</div>
                        </div>

                        <div class="row alt text ">
                            <div class="name"><img src="/{{ avatar_dir }}" style="width:100px"></div>
                            <div class="field">{{ form.uploadFile }}</div>
                            <div class="help">Select a gif, jpg, or png file less than 8Mb</div>
                        </div>


                        <div class="row alt submit">
                            <div class="name">&nbsp;</div>
                            <div class="field">
                                <input type="submit" name="submit" value="Submit" id="formsubmit" class="submit">
                            </div>
                        </div>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>


<!--

-->


</body>
</html>

Django_allthink/templates/main_page.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="vi" lang="vi">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Allthink Project - Group 6 </title>
    <link rel="shortcut icon" href="/site_media/images/favicon.ico">
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="/site_media/css/global.css">
    <link rel="stylesheet" type="text/css" href="/site_media/css/home.css">
    <script type="text/javascript" src="/site_media/js/common.js"></script>
</head>
<body>

<div id="wrapper">
    <div id="navwrapper" class="notranslate">
        <ul class="topnav" style="float: right;">
        </ul>
        <a href="/" id="logo" class="gradebook" title="Allthink"><b>Allthink</b></a>
        <ul class="topnav">
            <li>
                <a href="/login/" class="">Login </a>
            </li>
            <li>
                <a href="/signup/" class="">Signup </a>
            </li>
        </ul>
    </div>
    <div id="main" class="clearfix">
        <div style="width: 960px; position: relative; margin: auto; margin-top: 20px; top: -20px; ">
        </div>
        <div class="table text">
            <b><center> Wellcome to Group 6 - K55CA
            </center></b><br>
        </div>
        <script type="text/javascript">
            gid('input_usr').focus();</script>

    </div>
</div>

<!--
 
-->


</body>
</html>

Django_allthink/templates/search_form.html
<html>
<head>
</head>

<body>

	{% if entered %}
		<p> <font size="5" face="tahoma" style="color: #003580;"> Which lesson do you want :
                    {% if all_lessons %}
                        {% for lesson in all_lessons %}
                            {% if lesson not in lessons %}
                                <div>
                                <img src="/site_media/images/lecture.jpg" style="height: 24px; width: 24px"  >
                                    <font size="3" face="arial" color="#005685">
                                        <b>Lesson   : {{ lesson.lessonTitle }} - {{ lesson.subject }}</b></font>
                                    <font size="3" face="verada" color="#46a546">
                                        <div><b>Lecturer : {{ lesson.author }}</b></div></font>
                                </div>
                               <a href="/user/{{ username }}/lesson/{{ lesson.id }}/addref">
                                   <button style="position: relative; left : 650px; height: 25px; width: 100px;
                                   font-family: Tahoma; color: #a9302a ; font-weight: bold;">Add lesson</button></a>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <div class="row">
                            No lesson found.
                        </div>
                    {% endif %}
        </font></p>
	{% endif %}
	<form action="{% url search_form %}" method="GET">
	<table>
	{{ form }}
    <input type="hidden" name="u" value="{{ username }}"/>
	<tr>
		<th></th><td><input style="position: relative; left : 350px; height: 25px; width: 100px; font-family: Tahoma; color: #a9302a ; font-weight: bold;" type="submit" value="Search"/></td>
	</tr>
	</table>
	</form>
</body>
</html>

Django_allthink/templates/student_page.html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="vi" lang="vi">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="shortcut icon" href="/site_media/images/favicon.ico">
    <title>Allthink Lessons - {{ username }}</title>
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="/site_media/css/global.css">
    <script type="text/javascript" src="/site_media/js/common.js"></script>
    <script type="text/javascript" src="/site_media/js/jquery.js"></script>
</head>
<body>

<script type="text/javascript">
    $(document).ready(function() {
        $('#popclose').click(function() {
            location.reload();
        });
    });
</script>

<div id="wrapper">
    <div id="navwrapper" class="notranslate">
        <ul class="topnav" style="float: right;">
            <li>
                <a href="/user/{{ username }}/" class="nav" style="color:rgb(213,213,240);">
                    <img src="/{{ avatar_dir }}">
                    {{ fullname }} </a>
            </li>
            <li>
                <a href="/logout/" class="nav" style="color:rgb(213,213,240);">
                    Logout </a>
            </li>
        </ul>
        <a href="/user/{{ username }}/" id="logo" class="gradebook" title="gradebook"><b>gradebook</b></a>
        <ul class="topnav">
            <li>
                <a href="/user/{{ username }}/account" class="">Account </a>
                <ul>
                    <li><a href="/user/{{ username }}/account">Edit Account</a></li>
                    <li><a href="/user/{{ username }}/pic">Edit Picture</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div id="main" class="clearfix">
        <h1>Allthink Lessons</h1>

        <div class="tr">

            <div class="sidetools sideup">
                <img src="/{{ avatar_dir }}" class="sidepic">
            </div>

            <div style="position:absolute;left:200px;top:90px;right:0;bottom:0;z-index:2">


                <div style="width:100%;height:75px;background:url(/site_media/images/allthinkbg.jpg) 0 -68px repeat-x rgb(255,255,255);font-size:8pt;line-height:200%">
                    <a href="/user/{{ username }}/"
                       target="top"><img src="/site_media/images/allthinklogo2.png" style="float:left;margin-right:15px"></a>

                    <div style="max-width:770px">
                        Allthink
                    </div>
                </div>

                <div class="options">
                    <a href=""
                       onclick="popon('addpage');return false" class="title"><img
                            src="/site_media/images/page-add.png" class="upic"> Add New Lesson</a>
                </div>

                <div class="table bb">
                    {% if lessons %}
                        {% for lesson in lessons %}
                            <div class="row">
                                <a href="/user/{{ username }}/lesson/{{ lesson.id }}/view/1/0"
                                   target="_top"><img src="/site_media/images/lecture.jpg" class="postpic"></a>
                                <a href="/user/{{ username }}/lesson/{{ lesson.id }}/view/1/0"
                                   class="title" target="top"><b>{{ lesson.lessonTitle }}</b></a>

                                <div class="inline">
                                    <a href="/user/{{ username }}/lesson/{{ lesson.id }}/view/1/0">View Lesson</a>
                                    -
                                    <a href="/user/{{ username }}/lesson/{{ lesson.id }}/removeref" rel="tooltip" onclick="return confirm('Are you sure you want to unfollow this lesson ?')">Unfollow Lesson</a>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="row">
                            No lesson found.
                        </div>
                    {% endif %}

                </div>

            </div>

        </div>

        <div class="table" id="addpage" style="width:800px; height : 300px; display:none" title="Add Lesson">
{#            {% if all_lessons %}#}
{#                {% for lesson in all_lessons %}#}
{#                    {% if lesson not in lessons %}#}
{#                        <a href="/user/{{ username }}/lesson/{{ lesson.id }}/addref" class="row"> <img#}
{#                            src="/site_media/images/folder.png" class="upic"> {{ lesson.lessonTitle }} *** {{ lesson.user.fullname }} </a>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
{#            {% else %}#}
{#                <div class="row">#}
{#                    No lesson found.#}
{#                </div>#}
{#            {% endif %}#}
                <iframe style="width: 800px; height: 290px; position:absolute;left:0px;top:40px;right:0;bottom:0;z-index:2"
                        src="/search_form?u={{ username }}" id="appframe" border="0" frameborder="0"
                        ></iframe>
        </div>

    </div>
</div>

<div id="pop" class="off">
    <div id="poptop">
        <a href="javascript:popoff();void(0)" id="popclose" title="Close"><img src="/site_media/images/delete.png" alt="Close"></a>
        <div id="poptitle">&nbsp;</div>
    </div>
    <div id="popc"></div>
</div>
<!--
 
-->


</body>
</html>